# This is a basic workflow to help you get started with Actions

name: Update License Plate JSON on Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull events but only to the main branch.
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Python (you can adjust the version)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      # Run your script to generate/update JSON
      - name: Run update script
        run: python scripts/update_json.py

      # Echo a message to indicate completion
      - name: Echo completion message
        run: echo "JSON update completed successfully."
